<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OptionInfer>On</OptionInfer>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>
    </RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.AI.OpenAI" Version="2.2.0-beta.5" />
    <PackageReference Include="DevExpress.AIIntegration.WinForms" Version="25.2.2-beta" />
    <PackageReference Include="DevExpress.Win" Version="25.2.2-beta" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="9.7.1-preview.1.25365.4" />
  </ItemGroup>
  <ItemGroup>
    <None Update="WindowsForms.docx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>